from enum import StrEnum


class RunStatus(StrEnum):
    PENDING = "pending"
    DISPATCHING = "dispatching"
    LAUNCHING = "launching"
    WAITING_MANUAL = "waiting_manual"
    PROFILING = "profiling"
    RUNNING = "running"
    CAPTURE_COMPLETED = "capture_completed"
    POST_ANALYSIS_PENDING = "post_analysis_pending"
    QUALITY_REPORT_READY = "quality_report_ready"
    UPLOAD_PENDING = "upload_pending"
    UPLOADED_CONFIRMED = "uploaded_confirmed"
    LOCAL_DELETE_PENDING = "local_delete_pending"
    LOCAL_DELETED = "local_deleted"
    COMPLETED = "completed"
    NEEDS_MANUAL_SEED = "needs_manual_seed"
    MANUAL_REQUIRED = "manual_required"
    BLOCKED = "blocked"
    FAILED_LOW_YIELD = "failed_low_yield"
    FAILED_TOOL_ERROR = "failed_tool_error"
    FAILED_WORKER_LOST = "failed_worker_lost"
    FAILED_TIMEOUT = "failed_timeout"
    STUCK_RECOVERED = "stuck_recovered"
    CANCELLED = "cancelled"
    SKIPPED_RISK = "skipped_risk"
